### ISSUE TITLE
请问这什么情况

### ISSUE THREAD

**Issue by kentcc88** [gedoor/legado_web_source_editor#19]
请帮忙看看
![1](https://user-images.githubusercontent.com/18288037/195262757-e8ced2cf-ad56-4dbc-9057-be18921be2d7.png)
![3](https://user-images.githubusercontent.com/18288037/195556892-eb08f59b-db85-44d4-92d0-e733a5c8be33.png)
![2](https://user-images.githubusercontent.com/18288037/195262801-6574befc-9756-4122-9a52-2474cac5eb35.png)

log:
E:\
$ cd legado_web_source_editor\

E:\legado_web_source_editor (main -> origin)
$ npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

added 943 packages in 46s

E:\legado_web_source_editor (main -> origin)
$ npm serve
Unknown command: "serve"

Did you mean this?
    npm run serve # run the "serve" package script

To see a list of supported npm commands, run:
  npm help

E:\legado_web_source_editor (main -> origin)
$ npm run serve

> legado_web_source_editor@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...

 ERROR  Failed to compile with 1 error                                                           13:21:45
[eslint]
E:\legado_web_source_editor\src\components\editInput.vue
  12:14  error  Replace `changeHistory();restoreHeight()` with `⏎········changeHistory();⏎········restoreHeight();⏎···
···`  prettier/prettier
  91:33  error  Replace `attr.value.style·=·""` with `(attr.value.style·=·"")`                                              prettier/
prettier

E:\legado_web_source_editor\src\components\editInputList.vue
  28:6  error  Insert `,`  prettier/prettier

E:\legado_web_source_editor\src\router\index.js
  15:4  error  Insert `,`  prettier/prettier

E:\legado_web_source_editor\src\store\index.js
  16:46  error  Delete `·?`                                                                                              prettier/pretti er
  17:8   error  Replace `·state.bookSources·:·state.rssSources` with `·?·state.bookSources⏎········:·state.rssSources;`  pr
ettier/prettier
  35:53  error  Delete `·?`                                                                                              prettier/pretti er
  36:8   error  Replace `·state.bookSources` with `·?·state.bookSources⏎·······`                                         pretti
er/prettier
  74:9   error  Replace `"true"` with `true`                                                                             prettier/prettier
  75:9   error  Replace `"false":·false` with `false:·false,`                                                            prettier/prett
ier

E:\legado_web_source_editor\src\utils\bookSourceEditConfig.js
  587:4  error  Insert `,`  prettier/prettier

E:\legado_web_source_editor\src\utils\calcTextareaHeight.js
   14:3   error  Replace `'letter-spacing'` with `"letter-spacing"`
                  prettier/prettier
   15:3   error  Replace `'line-height'` with `"line-height"`
                  prettier/prettier
   16:3   error  Replace `'padding-top'` with `"padding-top"`
                  prettier/prettier
   17:3   error  Replace `'padding-bottom'` with `"padding-bottom"`
                  prettier/prettier
   18:3   error  Replace `'font-family'` with `"font-family"`
                  prettier/prettier
   19:3   error  Replace `'font-weight'` with `"font-weight"`
                  prettier/prettier
   20:3   error  Replace `'font-size'` with `"font-size"`
                  prettier/prettier
   21:3   error  Replace `'text-rendering'` with `"text-rendering"`
                  prettier/prettier
   22:3   error  Replace `'text-transform'` with `"text-transform"`
                  prettier/prettier
   23:3   error  Replace `'width'` with `"width"`
                  prettier/prettier
   24:3   error  Replace `'text-indent'` with `"text-indent"`
                  prettier/prettier
   25:3   error  Replace `'padding-left'` with `"padding-left"`
                  prettier/prettier
   26:3   error  Replace `'padding-right'` with `"padding-right"`
                  prettier/prettier
   27:3   error  Replace `'border-width'` with `"border-width"`
                  prettier/prettier
   28:3   error  Replace `'box-sizing'` with `"box-sizing",`
                  prettier/prettier
   34:44  error  Replace `'box-sizing'` with `"box-sizing"`
                  prettier/prettier
   36:22  error  Delete `·(`
                   prettier/prettier
   37:39  error  Replace `'padding-bottom'` with `"padding-bottom"`
                  prettier/prettier
   38:39  error  Replace `'padding-top'))⏎··)` with `"padding-top"))`
                    prettier/prettier
   41:21  error  Delete `·(`
                   prettier/prettier
   42:39  error  Replace `'border-bottom-width'` with `"border-bottom-width"`
                  prettier/prettier
   43:39  error  Replace `'border-top-width'))⏎··` with `"border-top-width")`
                    prettier/prettier
   46:37  error  Insert `.map(`
                  prettier/prettier
   47:5   error  Replace `.map(name·=>·`${name}:${style.getPropertyValue(name)}`)` with `(name)·=>·`${name}:${style.getPropertyValue(
name)}``              prettier/prettier
   48:3   error  Replace `··.join(';'` with `).join(";"`
                    prettier/prettier
   59:45  error  Replace `'textarea'` with `"textarea"`
                  prettier/prettier
   63:8   error  Replace `⏎····paddingSize,⏎····borderSize,⏎····boxSizing,⏎····contextStyle` with `·paddingSize,·border
Size,·boxSizing,·contextStyle·}·=`  prettier/prettier
   68:3   error  Replace `}·=` with `·`
                    prettier/prettier
   70:31  error  Replace `'style'` with `"style"`
                  prettier/prettier
   71:78  error  Replace `''` with `""`
                  prettier/prettier
   76:21  error  Replace `'border-box'` with `"border-box"`
                  prettier/prettier
   78:28  error  Replace `'content-box'` with `"content-box"`
                  prettier/prettier
   82:26  error  Replace `''` with `""`
                  prettier/prettier
   87:23  error  Replace `'border-box'` with `"border-box"`
                  prettier/prettier
   91:27  error  Replace `·minHeight·` with `minHeight`
                    prettier/prettier
   95:23  error  Replace `'border-box'` with `"border-box"`
                  prettier/prettier
  100:22  error  Replace `·height·` with `height`
                    prettier/prettier
  101:31  error  Insert `⏎···`
                     prettier/prettier
  104:2   error  Replace `;` with `⏎`
                  prettier/prettier

E:\legado_web_source_editor\src\views\sourceEditor.vue
   5:12  error  Insert `⏎·········`                                                 prettier/prettier
   8:56  error  Delete `>`                                                          prettier/prettier
   9:3   error  Insert `······>⏎`                                                   prettier/prettier
  46:41  error  Replace `data.selectTabKey·=·key` with `(data.selectTabKey·=·key)`  prettier/prettier
✖ 54 problems (54 errors, 0 warnings)
  54 errors and 0 warnings potentially fixable with the `--fix` option.

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
ERROR in [eslint]
E:\legado_web_source_editor\src\components\editInput.vue
  12:14  error  Replace `changeHistory();restoreHeight()` with `⏎········changeHistory();⏎········restoreHeight();⏎···
···`  prettier/prettier
  91:33  error  Replace `attr.value.style·=·""` with `(attr.value.style·=·"")`                                              prettier/
prettier

E:\legado_web_source_editor\src\components\editInputList.vue
  28:6  error  Insert `,`  prettier/prettier

E:\legado_web_source_editor\src\router\index.js
  15:4  error  Insert `,`  prettier/prettier

E:\legado_web_source_editor\src\store\index.js
  16:46  error  Delete `·?`                                                                                              prettier/pretti er
  17:8   error  Replace `·state.bookSources·:·state.rssSources` with `·?·state.bookSources⏎········:·state.rssSources;`  pr
ettier/prettier
  35:53  error  Delete `·?`                                                                                              prettier/pretti er
  36:8   error  Replace `·state.bookSources` with `·?·state.bookSources⏎·······`                                         pretti
er/prettier
  74:9   error  Replace `"true"` with `true`                                                                             prettier/prettier
  75:9   error  Replace `"false":·false` with `false:·false,`                                                            prettier/prett
ier

E:\legado_web_source_editor\src\utils\bookSourceEditConfig.js
  587:4  error  Insert `,`  prettier/prettier

E:\legado_web_source_editor\src\utils\calcTextareaHeight.js
   14:3   error  Replace `'letter-spacing'` with `"letter-spacing"`
                  prettier/prettier
   15:3   error  Replace `'line-height'` with `"line-height"`
                  prettier/prettier
   16:3   error  Replace `'padding-top'` with `"padding-top"`
                  prettier/prettier
   17:3   error  Replace `'padding-bottom'` with `"padding-bottom"`
                  prettier/prettier
   18:3   error  Replace `'font-family'` with `"font-family"`
                  prettier/prettier
   19:3   error  Replace `'font-weight'` with `"font-weight"`
                  prettier/prettier
   20:3   error  Replace `'font-size'` with `"font-size"`
                  prettier/prettier
   21:3   error  Replace `'text-rendering'` with `"text-rendering"`
                  prettier/prettier
   22:3   error  Replace `'text-transform'` with `"text-transform"`
                  prettier/prettier
   23:3   error  Replace `'width'` with `"width"`
                  prettier/prettier
   24:3   error  Replace `'text-indent'` with `"text-indent"`
                  prettier/prettier
   25:3   error  Replace `'padding-left'` with `"padding-left"`
                  prettier/prettier
   26:3   error  Replace `'padding-right'` with `"padding-right"`
                  prettier/prettier
   27:3   error  Replace `'border-width'` with `"border-width"`
                  prettier/prettier
   28:3   error  Replace `'box-sizing'` with `"box-sizing",`
                  prettier/prettier
   34:44  error  Replace `'box-sizing'` with `"box-sizing"`
                  prettier/prettier
   36:22  error  Delete `·(`
                   prettier/prettier
   37:39  error  Replace `'padding-bottom'` with `"padding-bottom"`
                  prettier/prettier
   38:39  error  Replace `'padding-top'))⏎··)` with `"padding-top"))`
                    prettier/prettier
   41:21  error  Delete `·(`
                   prettier/prettier
   42:39  error  Replace `'border-bottom-width'` with `"border-bottom-width"`
                  prettier/prettier
   43:39  error  Replace `'border-top-width'))⏎··` with `"border-top-width")`
                    prettier/prettier
   46:37  error  Insert `.map(`
                  prettier/prettier
   47:5   error  Replace `.map(name·=>·`${name}:${style.getPropertyValue(name)}`)` with `(name)·=>·`${name}:${style.getPropertyValue(
name)}``              prettier/prettier
   48:3   error  Replace `··.join(';'` with `).join(";"`
                    prettier/prettier
   59:45  error  Replace `'textarea'` with `"textarea"`
                  prettier/prettier
   63:8   error  Replace `⏎····paddingSize,⏎····borderSize,⏎····boxSizing,⏎····contextStyle` with `·paddingSize,·border
Size,·boxSizing,·contextStyle·}·=`  prettier/prettier
   68:3   error  Replace `}·=` with `·`
                    prettier/prettier
   70:31  error  Replace `'style'` with `"style"`
                  prettier/prettier
   71:78  error  Replace `''` with `""`
                  prettier/prettier
   76:21  error  Replace `'border-box'` with `"border-box"`
                  prettier/prettier
   78:28  error  Replace `'content-box'` with `"content-box"`
                  prettier/prettier
   82:26  error  Replace `''` with `""`
                  prettier/prettier
   87:23  error  Replace `'border-box'` with `"border-box"`
                  prettier/prettier
   91:27  error  Replace `·minHeight·` with `minHeight`
                    prettier/prettier
   95:23  error  Replace `'border-box'` with `"border-box"`
                  prettier/prettier
  100:22  error  Replace `·height·` with `height`
                    prettier/prettier
  101:31  error  Insert `⏎···`
                     prettier/prettier
  104:2   error  Replace `;` with `⏎`
                  prettier/prettier

E:\legado_web_source_editor\src\views\sourceEditor.vue
   5:12  error  Insert `⏎·········`                                                 prettier/prettier
   8:56  error  Delete `>`                                                          prettier/prettier
   9:3   error  Insert `······>⏎`                                                   prettier/prettier
  46:41  error  Replace `data.selectTabKey·=·key` with `(data.selectTabKey·=·key)`  prettier/prettier
✖ 54 problems (54 errors, 0 warnings)
  54 errors and 0 warnings potentially fixable with the `--fix` option.

webpack compiled with 1 error
Build finished at 13:22:15 by 0.000s

**Comment by Xwite** [comment]
先跑一下这个
```
npm run-script lint
```

**Comment by kentcc88** [comment]
> 先跑一下这个
> 
> ```
> npm run-script lint
> ```

我跑了这个命令，但打开页面是空白
![11111](https://user-images.githubusercontent.com/18288037/198227194-0f5e0cc8-c6fc-4e89-9a1b-c4adac42e16a.png)
![22222](https://user-images.githubusercontent.com/18288037/198227215-7b9cba83-7e95-4ee8-b545-9094b2a07a6b.png)
![33333](https://user-images.githubusercontent.com/18288037/198227230-e0759eb9-9274-4361-aaf4-72cc6f537f1b.png)

**Comment by Xwite** [comment]
see src/router/index.js
http://localhost:8080/#/bookSource
http://localhost:8080/#/rssSource

**Comment by kentcc88** [comment]
> see src/router/index.js http://localhost:8080/#/bookSource http://localhost:8080/#/rssSource

![lenovo20221116192309](https://user-images.githubusercontent.com/18288037/202167855-7c3155b3-dd84-48ff-b9a7-1114d1c16654.png)


![2022-11-18_154528](https://user-images.githubusercontent.com/18288037/202648623-329d2d4f-5b7b-4a77-86fa-a086cfb81322.png)

请问点击“调试源”之后一直转圈怎么解决？
