### ISSUE TITLE
调试的时候就这样

### ISSUE THREAD

**Issue by kentcc88** [gedoor/legado_web_source_editor#29]
> see src/router/index.js http://localhost:8080/#/bookSource http://localhost:8080/#/rssSource

![lenovo20221116192309](https://user-images.githubusercontent.com/18288037/202167855-7c3155b3-dd84-48ff-b9a7-1114d1c16654.png)

![2022-11-18_154528](https://user-images.githubusercontent.com/18288037/202648623-329d2d4f-5b7b-4a77-86fa-a086cfb81322.png)

请问点击“调试源”之后一直转圈怎么解决？

_Originally posted by @kentcc88 in https://github.com/gedoor/legado_web_source_editor/issues/19#issuecomment-1316839950_

**Comment by Xwite** [comment]
调试服务由阅读app提供

**Comment by kentcc88** [comment]
> 调试服务由阅读app提供

阅读APP已经开启了web服务，浏览器上的local storage位置也改成了相关ip和端口，但点调试还是不行，请指导下，谢谢

**Comment by Xwite** [comment]
调试端口应该是8081
