### ISSUE TITLE
Can you offer a readme about how to setup and use this editor?

### ISSUE THREAD

**Issue by crotoc** [gedoor/legado_web_source_editor#40]
Thaniks for the project. I am trying to create some source for legado. This is a great tool to start with! Can you teach me how to setup it and use it? I know how to code and parse html, but don't know how to use your editor. Thanks!

**Comment by Xwite** [comment]
You can use the web editor or internal editor in  [legado](https://github.com/gedoor/legado/releases)
## steps
* Install app to your Android phone or Android Emulator
* open app, click the forth bottom tab
### web editor
* click `Web service`
* copy the web ip, then open it in your browser
* click the second item `书源`
### internal editor
* click `Sources Management`

**Comment by crotoc** [comment]
Thanks very much!
