### ISSUE TITLE
调试源源快捷键不生效

### ISSUE THREAD

**Issue by AnLazyOtter** [gedoor/legado_web_source_editor#42]
如图，理论上在“快捷键”中设置了对应快捷键，比如Ctrl+Enter之后，在编辑源的界面中，按下设定的快捷键就能触发“调试源”功能，但目前实测来看好像没用……
![image](https://github.com/gedoor/legado_web_source_editor/assets/40395191/2938d743-ff3e-4b49-bdbc-ec43ac806a15)

阅读：3.23.051822
浏览器：edge版本 113.0.1774.42 (正式版本) (64 位)

**Comment by Xwite** [comment]
点保存没有

**Comment by AnLazyOtter** [comment]
> 点保存没有

点了的。
1. 点“编辑”
2. 按下CTRL+enter
3. 按ESC结束编辑
4. 点保存
5. 离开快捷键界面
6. 在调试源文本框输入“天魔”这个关键词
7. 点击编辑源界面任意文本框，如“搜索地址”
8. 按下CTRL+Enter
9. 无响应

**Comment by Xwite** [comment]
去掉第7步

**Comment by AnLazyOtter** [comment]
@Xwite 
抱歉之前忘记答复了：去掉第7步，那和在调试源编辑框中直接按ENTER有什么区别啊？
我记得之前版本中，调试源功能是无论是否焦点在调试源文本框中时，该快捷键都能生效呀。

**Comment by Xwite** [comment]
[hotkeys-js](https://www.npmjs.com/package/hotkeys-js/v/2.0.10)INPUT SELECT TEXTAREA 默认不处理
已经改好了

**Comment by AnLazyOtter** [comment]
> [hotkeys-js](https://www.npmjs.com/package/hotkeys-js/v/2.0.10)INPUT SELECT TEXTAREA 默认不处理 已经改好了

感谢~
那我理解，等到下次版本更新，应该就能正常了吧~
